export class Player {
  render(): HTMLElement {
    const player = document.createElement('div');
    player.className = 'universal-bottom-player';
    const playerContent = document.createElement('div');
    playerContent.className = 'universal-bottom-player-content';
    const playerInfo = document.createElement('div');
    playerInfo.className = 'universal-bottom-player-info';
    const preview = document.createElement('div');
    preview.className = 'universal-bottom-player-preview';
    const previewIcon = document.createElement('i');
    previewIcon.className = 'fas fa-music';
    preview.appendChild(previewIcon);
    playerInfo.appendChild(preview);
    const trackInfo = document.createElement('div');
    trackInfo.className = 'universal-bottom-player-track-info';
    const trackName = document.createElement('div');
    trackName.className = 'universal-bottom-player-track-name';
    trackName.textContent = 'Нет трека';
    trackInfo.appendChild(trackName);
    const trackArtist = document.createElement('div');
    trackArtist.className = 'universal-bottom-player-track-artist';
    trackArtist.textContent = '—';
    trackInfo.appendChild(trackArtist);
    playerInfo.appendChild(trackInfo);
    playerContent.appendChild(playerInfo);
    const progress = document.createElement('div');
    progress.className = 'universal-bottom-player-progress';
    const progressBar = document.createElement('div');
    progressBar.className = 'universal-bottom-player-progress-bar-container';
    const timeCurrent = document.createElement('span');
    timeCurrent.className = 'universal-bottom-player-time-current';
    timeCurrent.textContent = '0:00';
    progressBar.appendChild(timeCurrent);
    const bar = document.createElement('div');
    bar.className = 'universal-bottom-player-progress-bar';
    const fill = document.createElement('div');
    fill.className = 'universal-bottom-player-progress-fill';
    bar.appendChild(fill);
    progressBar.appendChild(bar);
    const timeTotal = document.createElement('span');
    timeTotal.className = 'universal-bottom-player-time-total';
    timeTotal.textContent = '0:00';
    progressBar.appendChild(timeTotal);
    progress.appendChild(progressBar);
    playerContent.appendChild(progress);
    const controls = document.createElement('div');
    controls.className = 'universal-bottom-player-controls';
    const prevBtn = document.createElement('button');
    prevBtn.className = 'universal-bottom-player-btn';
    const prevIcon = document.createElement('i');
    prevIcon.className = 'fas fa-step-backward';
    prevBtn.appendChild(prevIcon);
    controls.appendChild(prevBtn);
    const playBtn = document.createElement('button');
    playBtn.className = 'universal-bottom-player-btn universal-bottom-player-play';
    const playIcon = document.createElement('i');
    playIcon.className = 'fas fa-play';
    playBtn.appendChild(playIcon);
    controls.appendChild(playBtn);
    const nextBtn = document.createElement('button');
    nextBtn.className = 'universal-bottom-player-btn';
    const nextIcon = document.createElement('i');
    nextIcon.className = 'fas fa-step-forward';
    nextBtn.appendChild(nextIcon);
    controls.appendChild(nextBtn);
    playerContent.appendChild(controls);
    player.appendChild(playerContent);
    return player;
  }
}

